"use client";

import { createContext, useContext, useRef, type ReactNode } from "react";
import { useSharePdf } from "@/hooks/useSharePdf";

const ShareFileContext = createContext<File | null>(null);

/** Reads the PDF generated by the nearest enclosing PrintableWithShare — used
 * by a WhatsAppShareButton placed anywhere inside it, including in a server
 * component's header actions row. */
export function usePrintableShareFile(): File | null {
    return useContext(ShareFileContext);
}

/**
 * Wraps server-rendered printable content in the ref + useSharePdf that
 * WhatsAppShareButton needs, for pages (like the orderbook) that are server
 * components and can't hold a ref themselves. This is the client boundary;
 * everything below it — including a WhatsAppShareButton reading the file via
 * usePrintableShareFile — can stay wherever it's needed in the tree.
 */
export default function PrintableWithShare({ filename, children }: { filename: string; children: ReactNode }) {
    const printableRef = useRef<HTMLDivElement>(null);
    const file = useSharePdf(printableRef, filename);

    return (
        <div ref={printableRef} id="printable-area">
            <ShareFileContext.Provider value={file}>{children}</ShareFileContext.Provider>
        </div>
    );
}
